version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weber-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - weber-network

  #Nginx Service
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: weber-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8010:80"
    volumes:
      - ./:/var/www
    networks:
      - weber-network

  #MySQL Service
  # db:
  #   image: mariadb
  #   container_name: weber-db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3310:3306"
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: your_root_password
  #   volumes:
  #     - dbdata:/var/lib/mysql/
  #   networks:
  #     - weber-network

  # phpmyadmin:
  #   container_name: weber-phpmyadmin
  #   image: phpmyadmin
  #   ports:
  #     - 8081:80
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=weber-db
  #   depends_on:
  #     - db
  #   networks:
  #     - weber-network

#Docker Networks
networks:
  weber-network:
    driver: bridge

#Volumes
# volumes:
#   dbdata:
#     driver: local
